addLines({
  en: {
    Register: 'Register',
    Login: 'Login:',
    Password: 'Password:',
    SwitchToLogin: 'Switch to LOG IN page',
    REGISTER: 'REGISTER',
    loginalphanumeric: 'Login should only have latin letters, numbers and underscores',
    login3to16long: 'Login should be 3 to 16 characters long',
    passatleast6long: 'Password should be at least 6 characters long',
    registered: 'User _ successfully registered and may Log in now',
    occupied: 'Sorry, Login _ is already occupied, try another one',
  },
  ru: {
    Register: 'Регистрация',
    Login: 'Логин:',
    Password: 'Пароль:',
    SwitchToLogin: 'К странице ВХОДА',
    REGISTER: 'ЗАПИСАТЬ',
    loginalphanumeric: 'Логин может содержать лишь латинские буквы, цифры и подчёркивание',
    login3to16long: 'Логин должен быть от 3 до 16 символов',
    passatleast6long: 'Минимальный пароль - 6 символов',
    registered: 'Пользователь _ успешно добавлен и может Войти',
    occupied: 'Увы, логин _ уже занят, попробуйте другой',
  },
  ua: {
    Register: 'Реєстрація',
    Login: "Логін:",
    Password: "Пароль:",
    SwitchToLogin: "На сторінку ВХОДУ",
    REGISTER: "ЗАПИСАТИ",
    loginalphanumeric: 'Логін може містити лише латинські літери, цифри та підкреслення',
    login3to16long: 'Логін має бути від 3 до 16 символів',
    passatleast6long: 'Мінімальний пароль - 6 символів',
    registered: 'Користувач _ успішно зареєстрований і може Увійти',
    occupied: 'На жаль, логін _ вже зайнятий, спробуйте інший',
  }
})
