
CREATE TABLE IF NOT EXISTS pref_users (
  id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  login VARCHAR(32) NOT NULL,
  passhash VARCHAR(64) NOT NULL,
  dt_create DATETIME DEFAULT CURRENT_TIMESTAMP,
  dt_modify DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY unique_login (login)
);

CREATE TABLE IF NOT EXISTS pref_sessions (
  id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT(10) UNSIGNED NOT NULL,
  token1 VARCHAR(32),
  token2 VARCHAR(32),
  token3 VARCHAR(32),
  token4 VARCHAR(32),
  token5 VARCHAR(32),
  token6 VARCHAR(32),
  dt_create DATETIME DEFAULT CURRENT_TIMESTAMP,
  dt_modify DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pref_settings (
  user_id INT(10) UNSIGNED NOT NULL,
  lang VARCHAR(3),
  dt_create DATETIME DEFAULT CURRENT_TIMESTAMP,
  dt_modify DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY unique_user_id (user_id)
);
